# Generated by Django 5.1.1 on 2024-09-04 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('resumo', models.TextField()),
                ('conteudo', models.TextField()),
                ('imagem', models.ImageField(upload_to='noticias/')),
                ('categoria', models.CharField(choices=[('POLITICA', 'Política'), ('ARTE', 'Arte'), ('MEIO_AMBIENTE', 'Meio Ambiente'), ('TIROTEIO', 'Tiroteio'), ('ACIDENTE', 'Acidente'), ('ROCK_IN_RIO', 'Rock in Rio'), ('FUTEBOL', 'Futebol'), ('OUTROS', 'Outros')], max_length=50)),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=100)),
                ('conteudo', models.TextField()),
                ('data_comentario', models.DateTimeField(auto_now_add=True)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='noticias.noticia')),
            ],
        ),
    ]
